# Generated by Django 5.0.3 on 2024-10-12 23:22

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campuslogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Campuslogin',
                'verbose_name_plural': 'Campuslogin List',
            },
        ),
        migrations.CreateModel(
            name='Newslogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Newslogin',
                'verbose_name_plural': 'Newslogin List',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=150)),
                ('last', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('application', models.TextField(default='Choose your interest')),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], default='Choose your level', max_length=50)),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Register List',
            },
        ),
        migrations.CreateModel(
            name='Admincampusmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('blog', models.ImageField(upload_to='img/blog/')),
                ('person', models.ImageField(upload_to='img/person/')),
                ('content', models.CharField(max_length=128)),
                ('main', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admincampusmodel',
                'verbose_name_plural': 'Admincampusmodel List',
            },
        ),
        migrations.CreateModel(
            name='Adminnewsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('blog', models.ImageField(upload_to='img/blog/')),
                ('person', models.ImageField(upload_to='img/person/')),
                ('content', models.CharField(max_length=128)),
                ('main', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adminnewsmodel',
                'verbose_name_plural': 'Adminnewsmodel List',
            },
        ),
        migrations.CreateModel(
            name='Campuscomement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=150)),
                ('last', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Feed.admincampusmodel')),
            ],
            options={
                'verbose_name': 'Campuscomement',
                'verbose_name_plural': 'Campuscomement List',
            },
        ),
        migrations.CreateModel(
            name='Newscomement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=150)),
                ('last', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Feed.adminnewsmodel')),
            ],
            options={
                'verbose_name': 'Newscomement',
                'verbose_name_plural': 'Newscomement List',
            },
        ),
    ]
